[package]
name = "everything"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aer-core = { path = "../aer-core" }
aer-environment = { path = "../aer-environment" }
aer-workspace = { path = "../aer-workspace" }
clap.workspace = true
serde_json.workspace = true

[lints]
workspace = true
