use std::{
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use aer_repo::{
    CapabilityTier, EvidenceClass, FreshnessState, GraphDirection, GraphEdgeKind, IndexPolicy,
    PreciseRelation, PreciseSemanticBatch, PreciseSemanticEdge, RepositoryIndex, SearchQuery,
    TraversalBudget, repository_file_entity_id,
};

static COUNTER: AtomicU64 = AtomicU64::new(0);

struct Fixture {
    base: PathBuf,
    repo: PathBuf,
    index: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let nonce = COUNTER.fetch_add(1, Ordering::Relaxed);
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        let base = std::env::temp_dir().join(format!("aer-ri2-bench-{now}-{nonce}"));
        let repo = base.join("repo");
        let index = base.join("index.sqlite");
        fs::create_dir_all(repo.join("src")).expect("src dir");
        fs::create_dir_all(repo.join("tests")).expect("tests dir");
        fs::create_dir_all(repo.join("include")).expect("include dir");
        git(&repo, ["init"]);
        git(&repo, ["config", "user.email", "aer@example.invalid"]);
        git(&repo, ["config", "user.name", "AER Test"]);
        fs::write(
            repo.join("Cargo.toml"),
            "[package]\nname = \"ri2-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .expect("manifest");
        fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"ri2-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("lockfile");
        fs::write(
            repo.join("src/lib.rs"),
            "mod auth;\nmod session;\npub use auth::verify_token;\n",
        )
        .expect("lib source");
        fs::write(
            repo.join("src/auth.rs"),
            "use crate::session::session_is_valid;\npub fn verify_token(token: &str) -> bool { session_is_valid(token) }\n",
        )
        .expect("auth source");
        fs::write(
            repo.join("src/session.rs"),
            "pub fn session_is_valid(token: &str) -> bool { !token.is_empty() }\n",
        )
        .expect("session source");
        fs::write(
            repo.join("tests/auth_test.rs"),
            "use ri2_fixture::verify_token;\n#[test]\nfn rejects_empty_session() { assert!(!verify_token(\"\")); }\n",
        )
        .expect("test source");
        fs::write(
            repo.join("include/legacy.h"),
            "int legacy_verify_token(const char *token);\n",
        )
        .expect("fallback text");
        git(&repo, ["add", "."]);
        git(&repo, ["commit", "-m", "initial"]);
        Self { base, repo, index }
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.base);
    }
}

fn git<const N: usize>(repo: &Path, args: [&str; N]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(repo)
        .status()
        .expect("git command");
    assert!(status.success());
}

#[test]
fn repo_intel_bench_preserves_tier_provenance_and_bounded_graph_semantics() {
    let fixture = Fixture::new();
    let mut index =
        RepositoryIndex::open(&fixture.index, IndexPolicy::default()).expect("open RI2 index");
    let first = index.refresh(&fixture.repo).expect("first refresh");
    let snapshot = &first.snapshot.snapshot_id;

    let report = index
        .language_capability_report(snapshot)
        .expect("language capability report");
    assert!(report.tier1_files >= 4, "Rust files should have Tier-1 syntax");
    assert!(report.fallback_files >= 1, "unknown .h file must stay Tier-0 fallback");

    let views = index.ri2_view_states(snapshot).expect("view states");
    assert!(views.iter().any(|view| {
        view.view_name == "project"
            && view.freshness == FreshnessState::Current
            && view.capability_tier == CapabilityTier::Tier2Project
    }));
    assert!(views.iter().any(|view| {
        view.view_name == "precise_semantic"
            && view.freshness == FreshnessState::Unavailable
    }));
    let packages = index.build_packages(snapshot).expect("build packages");
    assert_eq!(packages.len(), 1);
    assert_eq!(packages[0].name, "ri2-fixture");

    let test_entity = repository_file_entity_id("tests/auth_test.rs").expect("test entity");
    let test_graph = index
        .graph_traverse(
            snapshot,
            &[test_entity],
            GraphDirection::Outgoing,
            TraversalBudget::default(),
        )
        .expect("test graph");
    assert!(test_graph.edges.iter().any(|edge| {
        edge.kind == GraphEdgeKind::Tests
            && edge.evidence.evidence_class == EvidenceClass::Inferred
    }));
    assert!(!test_graph.edges.iter().any(|edge| {
        edge.kind == GraphEdgeKind::Tests
            && edge.evidence.evidence_class == EvidenceClass::SemanticResolved
    }));

    let precise = index
        .ingest_precise_semantics(&PreciseSemanticBatch {
            snapshot_id: snapshot.clone(),
            producer_id: "fixture-scip".to_owned(),
            producer_version: "1".to_owned(),
            environment_fingerprint: "env-fixture-v1".to_owned(),
            edges: vec![PreciseSemanticEdge {
                source_path: "src/auth.rs".to_owned(),
                source_line: Some(2),
                source_symbol_id: None,
                relation: PreciseRelation::Call,
                target_symbol: "crate::session::session_is_valid".to_owned(),
                target_path: Some("src/session.rs".to_owned()),
            }],
        })
        .expect("precise semantic ingestion");
    assert_eq!(precise.len(), 1);
    assert_eq!(precise[0].evidence.evidence_class, EvidenceClass::SemanticResolved);
    assert_eq!(
        precise[0].evidence.environment_fingerprint.as_deref(),
        Some("env-fixture-v1")
    );
    assert!(index.ri2_view_states(snapshot).expect("updated views").iter().any(|view| {
        view.view_name == "precise_semantic" && view.freshness == FreshnessState::Current
    }));

    let auth_entity = repository_file_entity_id("src/auth.rs").expect("auth entity");
    let tiny = index
        .graph_traverse(
            snapshot,
            &[auth_entity],
            GraphDirection::Both,
            TraversalBudget {
                max_depth: 1,
                max_nodes: 1,
                max_edges: 1,
            },
        )
        .expect("bounded traversal");
    assert!(tiny.truncated, "bounded traversal must expose truncation");

    let retrieval = index
        .hybrid_retrieve(
            snapshot,
            &SearchQuery::new("verify token"),
            TraversalBudget {
                max_depth: 1,
                max_nodes: 32,
                max_edges: 64,
            },
        )
        .expect("hybrid retrieval");
    assert!(retrieval.iter().any(|hit| hit.path == "src/auth.rs"));
    assert!(retrieval.iter().all(|hit| !hit.why_relevant.is_empty()));
}

#[test]
fn repo_intel_bench_tracks_exact_content_continuity_and_dependency_invalidation() {
    let fixture = Fixture::new();
    let mut index =
        RepositoryIndex::open(&fixture.index, IndexPolicy::default()).expect("open RI2 index");
    let first = index.refresh(&fixture.repo).expect("first refresh");

    fs::rename(
        fixture.repo.join("src/session.rs"),
        fixture.repo.join("src/session_store.rs"),
    )
    .expect("rename session source");
    fs::write(
        fixture.repo.join("src/auth.rs"),
        "use crate::session::session_is_valid;\npub fn verify_token(token: &str) -> bool { !token.is_empty() && session_is_valid(token) }\n",
    )
    .expect("change auth source");

    let second = index.refresh(&fixture.repo).expect("second refresh");
    let changes = index
        .diff_snapshots(
            &first.snapshot.snapshot_id,
            &second.snapshot.snapshot_id,
        )
        .expect("snapshot diff");
    assert!(changes.changed_paths.contains(&"src/auth.rs".to_owned()));
    assert!(changes.deleted_paths.contains(&"src/session.rs".to_owned()));
    assert!(changes.added_paths.contains(&"src/session_store.rs".to_owned()));

    let continuity = index
        .symbol_continuity(
            &second.snapshot.repo_id,
            &first.snapshot.snapshot_id,
            &second.snapshot.snapshot_id,
        )
        .expect("symbol continuity");
    assert!(continuity.iter().any(|link| {
        link.from_symbol_id != link.to_symbol_id
            && link.evidence_class == EvidenceClass::Extracted
            && link.confidence_milli == 1000
    }));

    let frontier = index
        .invalidation_frontier(
            &first.snapshot.snapshot_id,
            &second.snapshot.snapshot_id,
            TraversalBudget {
                max_depth: 2,
                max_nodes: 64,
                max_edges: 128,
            },
        )
        .expect("invalidation frontier");
    let auth_entity = repository_file_entity_id("src/auth.rs").expect("auth entity");
    assert!(frontier.invalidated_entity_ids.contains(&auth_entity));
    assert!(frontier.invalidated_entity_ids.len() >= changes.invalidated_entity_ids.len());
}
