use std::{
    collections::BTreeSet,
    fs,
    path::{Path, PathBuf},
    process::Command,
    sync::atomic::{AtomicU64, Ordering},
    time::{SystemTime, UNIX_EPOCH},
};

use aer_repo::{
    CapabilityTier, EvidenceClass, FreshnessState, GraphDirection, GraphEdgeKind, IndexPolicy,
    PreciseRelation, PreciseSemanticBatch, PreciseSemanticEdge, RepositoryIndex, SearchQuery,
    TraversalBudget, language_profiles, repository_file_entity_id,
};

static COUNTER: AtomicU64 = AtomicU64::new(0);

struct Fixture {
    base: PathBuf,
    repo: PathBuf,
    index: PathBuf,
}

impl Fixture {
    fn new() -> Self {
        let nonce = COUNTER.fetch_add(1, Ordering::Relaxed);
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time")
            .as_nanos();
        let base = std::env::temp_dir().join(format!("aer-ri2-bench-{now}-{nonce}"));
        let repo = base.join("repo");
        let index = base.join("index.sqlite");
        fs::create_dir_all(repo.join("src")).expect("src dir");
        fs::create_dir_all(repo.join("tests")).expect("tests dir");
        fs::create_dir_all(repo.join("include")).expect("include dir");
        fs::create_dir_all(repo.join("tools")).expect("tools dir");
        fs::create_dir_all(repo.join("web")).expect("web dir");
        git(&repo, ["init"]);
        git(&repo, ["config", "user.email", "aer@example.invalid"]);
        git(&repo, ["config", "user.name", "AER Test"]);
        fs::write(
            repo.join("Cargo.toml"),
            "[package]\nname = \"ri2-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
        )
        .expect("manifest");
        fs::write(
            repo.join("Cargo.lock"),
            "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"ri2-fixture\"\nversion = \"0.1.0\"\n",
        )
        .expect("lockfile");
        fs::write(
            repo.join("src/lib.rs"),
            "mod auth;\nmod session;\npub use auth::verify_token;\n",
        )
        .expect("lib source");
        fs::write(
            repo.join("src/auth.rs"),
            "use crate::session::credential_is_active;\npub fn verify_token(token: &str) -> bool { credential_is_active(token) }\n",
        )
        .expect("auth source");
        fs::write(
            repo.join("src/session.rs"),
            "pub fn credential_is_active(value: &str) -> bool { !value.is_empty() }\n",
        )
        .expect("session source");
        fs::write(
            repo.join("tests/auth_test.rs"),
            "use ri2_fixture::verify_token;\n#[test]\nfn rejects_empty_session() { assert!(!verify_token(\"\")); }\n",
        )
        .expect("test source");
        fs::write(
            repo.join("tools/claims_probe.py"),
            "def parse_claims(blob):\n    return bool(blob)\n",
        )
        .expect("python source");
        fs::write(
            repo.join("web/credential.ts"),
            "export function normalizeCredential(value: string): string { return value.trim(); }\n",
        )
        .expect("typescript source");
        fs::write(
            repo.join("include/legacy.h"),
            "int legacy_validate_credential(const char *value);\n",
        )
        .expect("fallback text");
        git(&repo, ["add", "."]);
        git(&repo, ["commit", "-m", "initial"]);
        Self { base, repo, index }
    }
}

impl Drop for Fixture {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.base);
    }
}

fn git<const N: usize>(repo: &Path, args: [&str; N]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(repo)
        .status()
        .expect("git command");
    assert!(status.success());
}

fn relevant_yield(paths: impl IntoIterator<Item = String>, relevant: &BTreeSet<&str>) -> usize {
    paths
        .into_iter()
        .filter(|path| relevant.contains(path.as_str()))
        .count()
}

const BENCH_TEXT_PATHS: &[&str] = &[
    "src/lib.rs",
    "src/auth.rs",
    "src/session.rs",
    "tests/auth_test.rs",
    "tools/claims_probe.py",
    "web/credential.ts",
    "include/legacy.h",
];

fn lexical_only(repo: &Path, query: &str, limit: usize) -> Vec<String> {
    let terms = query
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|term| !term.is_empty())
        .map(str::to_ascii_lowercase)
        .collect::<Vec<_>>();
    let mut scored = BENCH_TEXT_PATHS
        .iter()
        .filter_map(|relative| {
            let text = fs::read_to_string(repo.join(relative))
                .ok()?
                .to_ascii_lowercase();
            let score = terms
                .iter()
                .map(|term| text.matches(term).count())
                .sum::<usize>();
            (score > 0).then_some((score, (*relative).to_owned()))
        })
        .collect::<Vec<_>>();
    scored.sort_by(|left, right| right.0.cmp(&left.0).then_with(|| left.1.cmp(&right.1)));
    scored.truncate(limit);
    scored.into_iter().map(|(_, path)| path).collect()
}

fn hashed_ngram_embedding(text: &str) -> [u32; 64] {
    let normalized = text
        .chars()
        .filter(|character| character.is_ascii_alphanumeric())
        .flat_map(char::to_lowercase)
        .collect::<String>();
    let bytes = normalized.as_bytes();
    let mut vector = [0_u32; 64];
    for ngram in bytes.windows(3) {
        let mut hash = 0xcbf29ce484222325_u64;
        for byte in ngram {
            hash ^= u64::from(*byte);
            hash = hash.wrapping_mul(0x100000001b3);
        }
        vector[(hash as usize) % vector.len()] =
            vector[(hash as usize) % vector.len()].saturating_add(1);
    }
    vector
}

fn embedding_only(repo: &Path, query: &str, limit: usize) -> Vec<String> {
    let query = hashed_ngram_embedding(query);
    let mut scored = BENCH_TEXT_PATHS
        .iter()
        .filter_map(|relative| {
            let text = fs::read_to_string(repo.join(relative)).ok()?;
            let vector = hashed_ngram_embedding(&text);
            let score = query
                .iter()
                .zip(vector.iter())
                .map(|(left, right)| u64::from(*left) * u64::from(*right))
                .sum::<u64>();
            (score > 0).then_some((score, (*relative).to_owned()))
        })
        .collect::<Vec<_>>();
    scored.sort_by(|left, right| right.0.cmp(&left.0).then_with(|| left.1.cmp(&right.1)));
    scored.truncate(limit);
    scored.into_iter().map(|(_, path)| path).collect()
}

fn graph_only(index: &RepositoryIndex, snapshot: &str, limit: usize) -> Vec<String> {
    let symbol = index
        .symbols(snapshot, "verify_token")
        .expect("graph-only symbol seed")
        .into_iter()
        .next()
        .expect("verify_token symbol");
    let graph = index
        .graph_traverse(
            snapshot,
            &[symbol.symbol_id],
            GraphDirection::Both,
            TraversalBudget {
                max_depth: 1,
                max_nodes: limit.max(1),
                max_edges: limit.saturating_mul(4).max(1),
            },
        )
        .expect("graph-only traversal");
    let mut paths = graph
        .nodes
        .into_iter()
        .filter_map(|node| node.path)
        .collect::<Vec<_>>();
    paths.sort();
    paths.dedup();
    paths.truncate(limit);
    paths
}

#[test]
fn repo_intel_bench_preserves_tier_provenance_and_improves_bounded_retrieval_yield() {
    let fixture = Fixture::new();
    let mut index =
        RepositoryIndex::open(&fixture.index, IndexPolicy::default()).expect("open RI2 index");
    let first = index.refresh(&fixture.repo).expect("first refresh");
    let snapshot = &first.snapshot.snapshot_id;

    let report = index
        .language_capability_report(snapshot)
        .expect("language capability report");
    assert!(
        report.tier1_files >= 6,
        "Rust, Python and TypeScript files should have Tier-1 syntax"
    );
    assert!(
        report.fallback_files >= 1,
        "unknown .h file must stay Tier-0 fallback"
    );
    let profiles = language_profiles();
    for required in ["rust", "python", "typescript"] {
        assert!(profiles.iter().any(|profile| {
            profile.language_id == required
                && profile.maximum_static_tier == CapabilityTier::Tier1Syntax
        }));
    }
    assert!(
        index
            .search(snapshot, &SearchQuery::new("parse_claims"))
            .expect("python retrieval")
            .hits
            .iter()
            .any(|hit| hit.path == "tools/claims_probe.py")
    );
    assert!(
        index
            .search(snapshot, &SearchQuery::new("normalizeCredential"))
            .expect("typescript retrieval")
            .hits
            .iter()
            .any(|hit| hit.path == "web/credential.ts")
    );

    let views = index.ri2_view_states(snapshot).expect("view states");
    assert!(views.iter().any(|view| {
        view.view_name == "project"
            && view.freshness == FreshnessState::Current
            && view.capability_tier == CapabilityTier::Tier2Project
    }));
    assert!(views.iter().any(|view| {
        view.view_name == "precise_semantic" && view.freshness == FreshnessState::Unavailable
    }));
    let packages = index.build_packages(snapshot).expect("build packages");
    assert_eq!(packages.len(), 1);
    assert_eq!(packages[0].name, "ri2-fixture");

    let test_entity = repository_file_entity_id("tests/auth_test.rs").expect("test entity");
    let test_graph = index
        .graph_traverse(
            snapshot,
            &[test_entity],
            GraphDirection::Outgoing,
            TraversalBudget::default(),
        )
        .expect("test graph");
    assert!(test_graph.edges.iter().any(|edge| {
        edge.kind == GraphEdgeKind::Tests && edge.evidence.evidence_class == EvidenceClass::Inferred
    }));
    assert!(!test_graph.edges.iter().any(|edge| {
        edge.kind == GraphEdgeKind::Tests
            && edge.evidence.evidence_class == EvidenceClass::SemanticResolved
    }));

    let precise = index
        .ingest_precise_semantics(&PreciseSemanticBatch {
            snapshot_id: snapshot.clone(),
            producer_id: "fixture-scip".to_owned(),
            producer_version: "1".to_owned(),
            environment_fingerprint: "env-fixture-v1".to_owned(),
            edges: vec![PreciseSemanticEdge {
                source_path: "src/auth.rs".to_owned(),
                source_line: Some(2),
                source_symbol_id: None,
                relation: PreciseRelation::Call,
                target_symbol: "crate::session::credential_is_active".to_owned(),
                target_path: Some("src/session.rs".to_owned()),
            }],
        })
        .expect("precise semantic ingestion");
    assert_eq!(precise.len(), 1);
    assert_eq!(
        precise[0].evidence.evidence_class,
        EvidenceClass::SemanticResolved
    );
    assert_eq!(
        precise[0].evidence.environment_fingerprint.as_deref(),
        Some("env-fixture-v1")
    );
    assert!(
        index
            .ri2_view_states(snapshot)
            .expect("updated views")
            .iter()
            .any(|view| {
                view.view_name == "precise_semantic" && view.freshness == FreshnessState::Current
            })
    );

    let auth_entity = repository_file_entity_id("src/auth.rs").expect("auth entity");
    let tiny = index
        .graph_traverse(
            snapshot,
            &[auth_entity],
            GraphDirection::Both,
            TraversalBudget {
                max_depth: 1,
                max_nodes: 1,
                max_edges: 1,
            },
        )
        .expect("bounded traversal");
    assert!(tiny.truncated, "bounded traversal must expose truncation");

    let query = SearchQuery {
        text: "verify token".to_owned(),
        limit: 4,
        min_score_micros: 100_000,
    };
    let lexical_paths = lexical_only(&fixture.repo, &query.text, query.limit);
    let current = index
        .search(snapshot, &query)
        .expect("current AER retrieval baseline");
    let graph_paths = graph_only(&index, snapshot, query.limit);
    let embedding_paths = embedding_only(&fixture.repo, &query.text, query.limit);
    let retrieval = index
        .hybrid_retrieve(
            snapshot,
            &query,
            TraversalBudget {
                max_depth: 1,
                max_nodes: 32,
                max_edges: 64,
            },
        )
        .expect("hybrid retrieval");
    let relevant = BTreeSet::from(["src/auth.rs", "src/session.rs"]);
    let lexical_yield = relevant_yield(lexical_paths, &relevant);
    let current_yield = relevant_yield(current.hits.into_iter().map(|hit| hit.path), &relevant);
    let graph_yield = relevant_yield(graph_paths, &relevant);
    let embedding_yield = relevant_yield(embedding_paths, &relevant);
    let hybrid_yield = relevant_yield(retrieval.iter().map(|hit| hit.path.clone()), &relevant);
    for (name, baseline_yield) in [
        ("lexical-only", lexical_yield),
        ("current-aer", current_yield),
        ("graph-only", graph_yield),
        ("hashed-ngram-embedding-only", embedding_yield),
    ] {
        assert!(
            hybrid_yield > baseline_yield,
            "RI2 hybrid retrieval must earn its complexity over {name}: hybrid={hybrid_yield}, baseline={baseline_yield}"
        );
    }
    assert!(retrieval.iter().any(|hit| hit.path == "src/auth.rs"));
    assert!(retrieval.iter().any(|hit| hit.path == "src/session.rs"));
    assert!(retrieval.iter().all(|hit| !hit.why_relevant.is_empty()));
    assert!(
        fs::metadata(&fixture.index).expect("index metadata").len() < 16 * 1024 * 1024,
        "small benchmark fixture must remain inside an explicit 16 MiB index budget"
    );
}

#[test]
fn repo_intel_bench_tracks_incremental_reuse_continuity_and_dependency_invalidation() {
    let fixture = Fixture::new();
    let mut index =
        RepositoryIndex::open(&fixture.index, IndexPolicy::default()).expect("open RI2 index");
    let first = index.refresh(&fixture.repo).expect("first refresh");

    fs::rename(
        fixture.repo.join("src/session.rs"),
        fixture.repo.join("src/session_store.rs"),
    )
    .expect("rename session source");
    fs::write(
        fixture.repo.join("src/auth.rs"),
        "use crate::session::credential_is_active;\npub fn verify_token(token: &str) -> bool { !token.is_empty() && credential_is_active(token) }\n",
    )
    .expect("change auth source");

    let second = index.refresh(&fixture.repo).expect("second refresh");
    assert!(
        second.reused_artifacts >= 4,
        "unchanged content should reuse content-addressed parse artifacts"
    );
    assert!(
        second.parsed_artifacts < first.parsed_artifacts,
        "incremental refresh should parse less unchanged content than the initial build"
    );
    let changes = index
        .diff_snapshots(&first.snapshot.snapshot_id, &second.snapshot.snapshot_id)
        .expect("snapshot diff");
    assert!(changes.changed_paths.contains(&"src/auth.rs".to_owned()));
    assert!(changes.deleted_paths.contains(&"src/session.rs".to_owned()));
    assert!(
        changes
            .added_paths
            .contains(&"src/session_store.rs".to_owned())
    );

    let continuity = index
        .symbol_continuity(
            &second.snapshot.repo_id,
            &first.snapshot.snapshot_id,
            &second.snapshot.snapshot_id,
        )
        .expect("symbol continuity");
    assert!(continuity.iter().any(|link| {
        link.from_symbol_id != link.to_symbol_id
            && link.evidence_class == EvidenceClass::Extracted
            && link.confidence_milli == 1000
    }));

    let second_views = index
        .ri2_view_states(&second.snapshot.snapshot_id)
        .expect("second view states");
    assert!(second_views.iter().any(|view| {
        view.view_name == "precise_semantic" && view.freshness == FreshnessState::Unavailable
    }));
    let old_session_entity =
        repository_file_entity_id("src/session.rs").expect("old session entity");
    assert!(
        index
            .graph_traverse(
                &second.snapshot.snapshot_id,
                &[old_session_entity],
                GraphDirection::Both,
                TraversalBudget::default(),
            )
            .is_err(),
        "stale deleted-file graph nodes must not silently survive in the new snapshot"
    );

    let frontier = index
        .invalidation_frontier(
            &first.snapshot.snapshot_id,
            &second.snapshot.snapshot_id,
            TraversalBudget {
                max_depth: 2,
                max_nodes: 64,
                max_edges: 128,
            },
        )
        .expect("invalidation frontier");
    let auth_entity = repository_file_entity_id("src/auth.rs").expect("auth entity");
    assert!(frontier.invalidated_entity_ids.contains(&auth_entity));
    assert!(frontier.invalidated_entity_ids.len() >= changes.invalidated_entity_ids.len());
}
